# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSwipetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_swipetest(self):
    self.driver.get("https://mini-search.shopping.naver.com/ns/search?query=%EA%B0%80%EB%94%94%EA%B1%B4")
    self.driver.set_window_size(2514, 1456)

    element = self.driver.find_element(By.CSS_SELECTOR, ".customRecommendFlickingProductList_item__2HKtZ:nth-child(2) .customRecommendFlickingProductList_product_item__3Q93J:nth-child(4) .miniProductCard_link__1X65D")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".miniProductCard_is_hovering__YcjO9 > .miniProductCard_link__1X65D").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".miniProductCard_is_hovering__YcjO9 > .miniProductCard_link__1X65D")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".layout_wrap__hjxgU").click()
  
